// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Upflux_WebService.Data;

#nullable disable

namespace Upflux_WebService.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Upflux_WebService.Core.Models.Licence", b =>
                {
                    b.Property<string>("LicenceKey")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("license_key");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expiration_date");

                    b.Property<int>("MachineId")
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    b.Property<string>("ValidityStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("validity_status");

                    b.HasKey("LicenceKey");

                    b.ToTable("Licenses");
                });

            modelBuilder.Entity("Upflux_WebService.Core.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("machine_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("MachineId"));

                    b.Property<string>("ActivityStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("activity_status");

                    b.Property<string>("MachineStatus")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("machine_status");

                    b.Property<float?>("MemoryUsage")
                        .HasColumnType("float")
                        .HasColumnName("memory_usage");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
